language: clojure
sudo: false
env:
  global:
    - SSH_OPTS="-i .travis/deploy_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    - PROGRAM=nginx-auth
before_install:
  - openssl aes-256-cbc -K $encrypted_3d8a1c41107e_key -iv $encrypted_3d8a1c41107e_iv
    -in .travis/deploy_key.pem.enc -out .travis/deploy_key.pem -d
after_success:
  - lein uberjar
  - chmod 600 .travis/deploy_key.pem
  - scp $SSH_OPTS -P 1988 target/${PROGRAM}.jar travis-ci@penelope.cfrq.net:/var/tmp/${PROGRAM}.jar
  - ssh $SSH_OPTS -p 1988 travis-ci@penelope.cfrq.net /opt/${PROGRAM}/update-from-travis
